pipeline:
  name: Manage Env
  identifier: Manage_Env
  projectIdentifier: FredSandBox
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: MgtEnv
        identifier: MgtEnv
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: <+input>
            serviceInputs: <+input>
          environment:
            environmentRef: <+input>
            deployToAll: false
            environmentInputs: <+input>
            serviceOverrideInputs: <+input>
            infrastructureDefinitions: <+input>
          execution:
            steps:
              - parallel:
                  - step:
                      type: K8sRollingDeploy
                      name: RollingDeploy
                      identifier: RollingDeploy
                      spec:
                        skipDryRun: false
                        pruningEnabled: false
                      timeout: 10m
                      when:
                        stageStatus: Success
                        condition: <+pipeline.variables.Action> == "RollingDeploy"
                      failureStrategies: []
                  - step:
                      type: K8sDelete
                      name: Delete
                      identifier: Delete
                      spec:
                        deleteResources:
                          type: ReleaseName
                          spec:
                            deleteNamespace: false
                      timeout: 10m
                      when:
                        stageStatus: Success
                        condition: <+pipeline.variables.Action> == "Remove"
                      failureStrategies: []
                  - stepGroup:
                      name: CanaryDeploy
                      identifier: CanaryDeploy
                      steps:
                        - step:
                            type: K8sCanaryDeploy
                            name: K8sCanaryDeploy
                            identifier: K8sCanaryDeploy
                            spec:
                              skipDryRun: false
                              instanceSelection:
                                type: Count
                                spec:
                                  count: 1
                            timeout: 10m
                        - step:
                            type: K8sRollingDeploy
                            name: K8sRollingDeploy
                            identifier: K8sRollingDeploy
                            spec:
                              skipDryRun: false
                              pruningEnabled: false
                            timeout: 10m
                        - step:
                            type: K8sCanaryDelete
                            name: K8sCanaryDelete
                            identifier: K8sCanaryDelete
                            spec: {}
                            timeout: 10m
                      when:
                        stageStatus: Success
                        condition: <+pipeline.variables.Action> == "CanaryDeploy"
                      failureStrategies: []
                      spec: {}
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  variables:
    - name: Action
      type: String
      description: ""
      value: <+input>.allowedValues(Remove,RollingDeploy,CanaryDeploy)
