pipeline:
  name: STO - Image
  identifier: STO_Image
  projectIdentifier: FredSandBox
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Scan Image
        identifier: Scan_Image
        type: SecurityTests
        spec:
          cloneCodebase: false
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: gkefred
              namespace: dev-gke-fred
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Background
                  name: DinD
                  identifier: DinD
                  spec:
                    connectorRef: FredDockerRegistry
                    image: docker:dind
                    shell: Sh
                    privileged: true
                    entrypoint:
                      - dockerd-entrypoint.sh
                    imagePullPolicy: IfNotPresent
              - step:
                  type: Run
                  name: Scan
                  identifier: Scan
                  spec:
                    connectorRef: FredDockerRegistry
                    image: aquasec/trivy
                    shell: Sh
                    command: |-
                      sleep 5
                      trivy image --scanners vuln -f json -o /var/run/results.json $IMAGE
                    privileged: true
                    envVariables:
                      IMAGE: <+stage.variables.IMAGE>
                    imagePullPolicy: IfNotPresent
                    resources:
                      limits:
                        memory: 2G
                        cpu: "1"
              - step:
                  type: AquaTrivy
                  name: AquaTrivy
                  identifier: AquaTrivy
                  spec:
                    mode: ingestion
                    config: default
                    target:
                      name: trivy
                      type: container
                      variant: <+stage.variables.IMAGE>
                    advanced:
                      log:
                        level: info
                    privileged: false
                    imagePullPolicy: IfNotPresent
                    ingestion:
                      file: /var/run/results.json
          sharedPaths:
            - /var/run/
        variables:
          - name: IMAGE
            type: String
            description: ""
            value: <+input>
